"""Added authors table and foreign key to books

Revision ID: b3d2b8840b84
Revises: 8ea5732f4a98
Create Date: 2025-04-02 10:36:32.205902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d2b8840b84'
down_revision: Union[str, None] = '8ea5732f4a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authors_id', table_name='authors')
    op.drop_table('authors')
    op.drop_index('ix_books_id', table_name='books')
    op.drop_index('ix_books_title', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.create_index('ix_books_title', 'books', ['title'], unique=False)
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='authors_pkey'),
    sa.UniqueConstraint('name', name='authors_name_key')
    )
    op.create_index('ix_authors_id', 'authors', ['id'], unique=False)
    # ### end Alembic commands ###
